### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by YumiSuki** [sneas/img-comparison-slider#78]
Hello everyone,

I am trying to use img-comparison-slider recently with Nuxt3 and got some error. 

I have install the following dependency: 
- "nuxt3": "^3.0.0-27506322.90da56a",
- "@img-comparison-slider/vue": "^7.5.2",

And here is some error log: 
```
ℹ Vite client warmed up in 2682ms                                                                                                                                                                       23:02:41
ℹ Vite server warmed up in 2066ms                                                                                                                                                                       23:02:44
✔ Vite server built in 6301ms                                                                                                                                                                           23:02:48
✔ Nitro built in 474 ms                                                                                                                                                                           nitro 23:02:48
ReferenceError: window is not defined
    at /home/Desktop/my-project/node_modules/img-comparison-slider/dist/index.js:1:3640
    at /home/Desktop/my-project/node_modules/img-comparison-slider/dist/index.js:1:10077
    at Object.<anonymous> (/home/Desktop/my-project/node_modules/img-comparison-slider/dist/index.js:1:10081)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:196:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
```

So, please kindly help. Thanks.

**Comment by TangoPJ** [comment]
@YumiSuki First you need to make it a plugin. Second you need to make your plugin client side only
`plugins: [
  { src: '~/plugins/img-comparison-slider', mode: 'client' }
]`
