### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by garmede** [sneas/img-comparison-slider#88]
Hello!

I'm trying img-comparison-slider to use vuepress v2 component.
and it's works with vuepress v2 'dev mode'.

my dependencies here:
```json
"devDependencies": {
    "@img-comparison-slider/vue": "^7.6.0",
    "@vuepress/plugin-register-components": "^2.0.0-beta.49",
    ...
}
```

but site build failed with before message.
```
info Initializing VuePress and preparing data...
⠼ Compiling with vite
(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
✔ Compiling with vite - done
✖ Rendering pages - failed
ReferenceError: document is not defined
    at E:\github\docs\node_modules\img-comparison-slider\dist\index.js:1:3640
    at E:\github\docs\node_modules\img-comparison-slider\dist\index.js:1:10336
    at Object.<anonymous> (E:\github\docs\node_modules\img-comparison-slider\dist\index.js:1:10340)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (E:\github\docs\node_modules\@img-comparison-slider\vue\dist\index.umd.js:6:1)
```

my component vue file:
```vue
<template>
    <ClientOnly>
        <ImgComparisonSlider>
            <!-- eslint-disable -->
            <img slot="first" :src=before />
            <img slot="second" :src=after />
            <!-- eslint-enable -->
        </ImgComparisonSlider>
    </ClientOnly>
</template>

<script>
import { ImgComparisonSlider } from '@img-comparison-slider/vue';

export default {
    props: {
        before: String,
        after: String,
    },
    components: {
        ImgComparisonSlider
    },
};
</script>
```

Please help me!

**Comment by sneas** [comment]
Hi @garmede, have you considered dynamic component import instead?

```vue
<script>
import { defineComponent, defineAsyncComponent } from 'vue'

export default defineComponent({
  name: 'App',
  components: {
    ImgComparisonSlider: defineAsyncComponent(() => import('@img-comparison-slider/vue').then(({ImgComparisonSlider}) => ImgComparisonSlider
    ))
  },
})
</script>
```

**Comment by garmede** [comment]
It's works!
I haven't been able to find a way to apply it.
Thank you! @sneas !
